### PR TITLE
Creating and rendering SDK keys

### PR DESCRIPTION
**Pull request by l-jdavies**
This is the front and back-end implementation of displaying an SDK key to users and enabling them to generate a new one.

- When a user visits the `/account` page, the database is queried to determine if there are any sdk keys with an `is_active` property of `true`
- If there is an active key, this is returned and rendered; if there isn't one is created, stored in the db, and rendered to the user
- If a user clicks on the button to generate a new sdk key, the existing one will be updated in the db and given an `is_active` value of `false` then a new key is generated, added to the db with an `is_active` value is `true`, which is then rendered to the user.

### CODE REVIEW

**Comment by l-jdavies** [comment]
Also added integration with JetStream

**Comment by l-jdavies** [comment]
This needs a bit more work, it's too unstable

**Comment by l-jdavies** [comment]
This should be up and running now.

**Comment by emctackett** [comment]
woohoo! 🥳

**Review by emctackett — APPROVED** [review]

**Review by kaledoux — CHANGES_REQUESTED** [review]
docker/docker-compose.yml should have the test db initialized!

**Pull request merged**
