### PR TITLE
Mock tests controller

### PR DESCRIPTION
**Pull request by kaledoux**
This PR builds on the previous testing branch to include testing the `eventLogController` and the `flagController`. 

**Mocks:**
To test the responses of the controller methods in either file, I made use of mocks for the requests and responses that needed to be passed in as arguments. These mocks are essentially dummy data that gets fed into the methods, to provide them with the requisite context to complete the db queries within. There is also some mocking of express method functionality to ensure that the data returned by methods like `res.json()` would be accessible for analysis.
A mocked request object might look like so:
```js
const mockRequest = {
  flag : {
    title       : 'TEST',
    description : 'testing',
    rollout     : 33,
    is_active   : false,
    version     : 1
  }
};
```
While a mocked Response might look like so (note the mocked `json` function therein):
```js
  const mockResponse = {
    json : jest.fn().mockImplementation((result) => {
		responseObject = result;
  })
```

**noop method:**
Another tool used in the mocking process was a No-op (non-functional) method that could be used to stand in for middleware that was being called in a controller method. Since the method expects to pass the response to middleware in most cases, we simply use a noop function to satisfy this requirement while extracting the relevant data via the mocking function.
```js
const noop = () => {
  // do nothing
};
```
So in a method like `getFlag` we can make use of a mockedRequest, a mocked response, and a no-op, to test what data is actually being returned:
```js
const sendFlag = (req, res, next) => {
  const flag = req.flag;
  res.json({ flag });
};
```
```js
test('sendFlag should respond with a flag in json format', async () => {
  const mockRequest = {
    flag : {
      title       : 'TEST',
      description : 'testing',
      rollout     : 33,
      is_active   : false,
      version     : 1 
    }
  };
  let responseObject = {};
    const mockResponse = {
      json : jest.fn().mockImplementation((result) => {
        responseObject = result;
      })
    };

    await sendFlag(mockRequest, mockResponse, noop);

    expect(responseObject.flag).toHaveProperty('title', 'TEST');
...etc
```
**forceExit:**
Due to the logging methods that are called within many of the controller methods, I overrode many some of the publishing methods to prevent their including NATS operations as part of the return data evaluation.
Some nested logging and publishing calls can cause some of the tests to persist and raise warnings from jest because there are logs being attempted after the test has already finished.
To cut the tests as soon as the results have been compared, I call jest with the `--forceExit` flag, which will terminate the test even if there are unresolved async calls.

### CODE REVIEW

**Comment by jimzhe842** [comment]
Awesome job Kyle! Seems like you have the controller tests figured out and picked up from where we stopped last time.

**Comment by emctackett** [comment]
Great job!  🙌  You put in a ton of hard work here.

This is what I see when I run the tests:

Screen Shot 2021-07-16 at 7 24 28 AM

I get a few errors but perhaps more noteably is it looks like some async operations aren't finishing and Jest is having to force quit. Not sure if this is an issue on my end but I would love to pair on this @kaledoux 😄

**Comment by kaledoux** [comment]
Thanks for bringing this to my attention! It seems that there is something amiss behind the scenes.

The issue seems to be that the test command was interacting with the test database which did not have the same schema (missing the `rollout` column) as the main db. So, the tests failed.

They all worked on my end, because for whatever reason, the command we use in the npm script for testing was not setting the port properly in my environment, and was defaulting to the port of the main db.

**Good news:**
with an update to the test db schema, and a rebuild of the docker environment for postgres, the tests should work as expected.
**Bad news:** 
there may be some difference in how the port settings are working between OSs. The script that was working for you all to set the port : 
```js
"scripts": {
  "test": "set PORT=5430 && jest --runInBand --forceExit --silent"
```
Needs to be set as follows for the env variable to be set properly on my end:
```js
"scripts": {
  "test": "PORT=5430 jest --runInBand --forceExit --silent",
```

At this point, the tests seem to be behaving as expected. I have only the postgres test db up and can run the tests without issue. I've printed the env variables and confirmed that the port setting is correct. 
Screenshot from 2021-07-16 09-43-07

**SO...**
We may just need to be aware of env variable setting differences. But perhaps we can test the scripts out as is to see if there are any cross platform issues before going down that path.
Sending updates to PR now with schema changes.

**Comment by l-jdavies** [comment]
This is all looking good on my end. Great job, this was a lot of work!
image

**Review by emctackett — APPROVED** [review]

**Pull request merged**
