### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by kaledoux**
### This PR contains test suites for the `server/lib/db` folder.

The previous work on this branch needed to be merged with the updated `main` branch, as there were significant changes to the directories and files involved. The testing files and all concerned code, like helpers, imports, etc have all been modified to reflect the changes.

**A new database:**
To configure testing in a realistic, but isolated fashion, we have added the creation of a separate postgres docker instance for dedicated testing to the docker compose file. This means that for the tests to run correctly, you will need to tear down and rebuild docker with `docker-compose`.
Note that the test db listens on port `5430`.

**Port Configuration:**
To ensure the methods for connecting to and querying the database are connecting to the correct test database, we set the environment variable for `PORT` in our npm scripts. It will set `PORT` to `5432` during dev and `5430` during testing.

New tests have been added to capture the additions of new methods in the `lib/db/flags.js` file and ensure functionality of those methods in isolation. Existing tests were refactored and renamed to be more explicit and to reflect the changes in source code.

I did attempt to test the error conditions of the methods, but the new structure of the methods for error output (logging an error with `console.error` then throwing an `HttpError`) have proved quite difficult to capture. The console errors have been captured with mocking functions, but the tests themselves are still not returning the values needed to verify the error. This is an area that will need further research and work to bring fully online. 

**A note on concurrency and database operations:**
Jest runs test files concurrently. Our tests make use of writing to and deleting from the `feature-flag-postgres-test` database with every test. These two factors combined, means that sometimes the concurrent operations can conflict and throw off a test result. To combat this, we run the test script with the command `--runInBand` to disable concurrent testing.

### CODE REVIEW

**Comment by emctackett** [comment]
Awesome work, guys! I did have a single test fail the first time I ran the tests, but in subsequent runs they all passed. :+1: 

I wanted to ask-- is there a way to reduce the excessive output?  This is just a small portion of the output in my terminal when I ran the tests.
Screen Shot 2021-07-15 at 10 49 19 AM

**Comment by emctackett** [comment]
Or maybe those are all just logs within our code. 🤔  If so maybe we can trim down all of the console logs in our code, and/or see if we can suppress some of that output when the tests run.

**Comment by emctackett** [comment]
Added a `--silent` flag to our test command in `package.json`.  Now the terminal output is a bit more clear for the user:
Screen Shot 2021-07-15 at 11 01 51 AM

**Review by emctackett — APPROVED** [review]
🥇  Awesome work!

**Comment by l-jdavies** [comment]
Awesome work guys!

**Pull request merged**
