### PR TITLE
Account page

### PR DESCRIPTION
**Pull request by emctackett**
This is just a UI update that can be hooked up to backend functionality @l-jdavies is working on.  Here is what it looks like

When no key has been created (this would be the initial state I guess)

Screen Shot 2021-07-15 at 2 09 15 PM

When a key exists, and they have the option to generate a new one. The user is given the option to click the link to copy the key to clipboard.

Screen Shot 2021-07-15 at 2 10 31 PM

### CODE REVIEW

**Comment by emctackett** [comment]
@l-jdavies this is all just UI stuff ready to be hooked up to the back-end when you're finished!

**Comment by l-jdavies** [comment]
Awesome work, thank you! I hope it's ok but I've merged this in with my `backend-sdk-keys` so I can link up with the backend.

**Comment by emctackett** [comment]
> Awesome work, thank you! I hope it's ok but I've merged this in with my `backend-sdk-keys` so I can link up with the backend.

Perfect! Should I close this PR and you'll open a new one with your code?

**Comment by l-jdavies** [comment]
I think that's the easiest.

**Pull request closed without merging**
